#  Pytorch
---
## [1] Tensor 생성

In [1]:
import torch

In [2]:
torch.__version__

'1.12.1+cpu'

In [16]:
# [기본] tensor(data)
t1=torch.tensor([1,2,3], dtype=torch.int32)

In [17]:
type(t1), t1.shape, t1.dtype, t1.device, t1.ndim 

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'), 1)

In [7]:
t2=torch.tensor([1.,2,3])

In [9]:
type(t2), t2.shape, t2.dtype, t2.device, t2.ndim

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'), 1)

In [10]:
t3=torch.tensor([[1.,2,3],[1,2,2]])

In [11]:
type(t3), t3.shape, t3.dtype, t3.device, t3.ndim

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'), 2)

In [21]:
t4=torch.ones(size=(10,3))
t4

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
t4=torch.zeros(size=(10,3))
t4

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
# t3자료형과 똑같은 형태로 0으로 채움
t4=torch.zeros_like(t3)
t4

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
# 0.0~1.0 사이의 값 랜덤하게 지정
torch.rand_like(t3)

tensor([[0.6231, 0.4298, 0.9184],
        [0.1336, 0.1832, 0.7250]])

In [28]:
t3.ndim, t3.shape

(2, torch.Size([2, 3]))

In [29]:
# 행 -> [행인덱스]
t3[0],  t3[1]

(tensor([1., 2., 3.]), tensor([1., 2., 2.]))

In [31]:
# 열 -> [행, 열]
t3[:,0], t3[0,1], t3[:, 2]

(tensor([1., 1.]), tensor(2.), tensor([3., 2.]))

In [32]:
t3.mean(), t3.min(), t3.max()

(tensor(1.8333), tensor(1.), tensor(3.))

In [33]:
# 원본의 값을 바꾸는 메서드 뒤에 '_' 붙음
t3.add_(2)

tensor([[3., 4., 5.],
        [3., 4., 4.]])

In [34]:
t3.mul_(3)

tensor([[ 9., 12., 15.],
        [ 9., 12., 12.]])

In [35]:
tn=t3.numpy()

In [36]:
tn[0]

array([ 9., 12., 15.], dtype=float32)

In [37]:
tn[0]=100
tn

array([[100., 100., 100.],
       [  9.,  12.,  12.]], dtype=float32)

In [38]:
torch.cuda.is_available()

False