# Numpy 패키지

 - pandas에서 데이터를 저장 및 처리에 사용되는 패키지
 
 - 외부 패키지로 반드시 설치 필요
 
 - 고속 데이터 처리, 수치 계산 수행 패키지
 
 - 머신러닝/딥러닝용 패키지 Scikit-lern, Tensorflow, PyTorch, Keras 등에서도 내부 데이터 저장 및 수치 계산에 사용되는 패키지
 
 - [중요] 동일한 데이터 타입의 데이터를 저장하는 배열(Array) 타입!
 
 - 설치 : !pip install numpy

In [1]:
# 버전 확인
import numpy as np

np.__version__

'1.21.5'

In [2]:
# ndarray 객체 생성 하기 ---> numpy.array()

arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [7]:
# ndarray 객체 속성 확인하기
# 객체변수명.속성명
# ndim : 차원 (예 : 1,2,3....)
# shape : 형태 (예 : 갯수, (행,열), (면,행,열))
# dtype : 데이터 타입
# itemsize : 배열 요소의 바이트 크기
# size : 배열 요소 갯수
print(arr1.ndim, arr1.shape, arr1.dtype,arr1.itemsize,arr1.size, sep='\n')

1
(3,)
int32
4
3


In [10]:
# 배열의 요소 즉 아이템, 원소 접근하기
# 0-base 인덱스 자동 지정 => 객체변수명[인덱스]
print(f'객체변수명 arr1 => {arr1} ')
print(f'객체변수명 arr1[0] => {arr1[0]} ')
print(f'객체변수명 arr1[0] => {arr1[1]} ')

객체변수명 arr1 => [1 2 3] 
객체변수명 arr1[0] => 1 
객체변수명 arr1[0] => 2 


In [14]:
# 모든 값을 1으로 채워서 ndarray 객체 생성 함수 => ones()
arr2=np.array([1,1,1,1])
arr2=np.ones(4,dtype=np.int16)
arr2

array([1, 1, 1, 1], dtype=int16)

In [15]:
print(arr2.ndim, arr2.shape, arr2.dtype,arr2.itemsize,arr2.size, sep='\n')

1
(4,)
int16
2
4


In [16]:
print(f'객체변수명 arr2 => {arr2} ')
print(f'객체변수명 arr2[0] => {arr2[0]} ')
print(f'객체변수명 arr2[0] => {arr2[1]} ')

객체변수명 arr2 => [1 1 1 1] 
객체변수명 arr2[0] => 1 
객체변수명 arr2[0] => 1 


In [19]:
arr3=np.zeros(4,dtype=np.int32)
arr3

array([0, 0, 0, 0])

In [20]:
arr4=np.full(4,2)
arr4

array([2, 2, 2, 2])

In [27]:
# 초기화하지 않고 ndarray 객체 생성 =>  numpy.empty()
arr5=np.empty((2,3))
arr5

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [9.34609111e-307, 1.42413555e-306, 1.78019082e-306]])

In [ ]:
# 2차원 형태의 ndarray 객체 생성

In [32]:
arr6=np.zeros((3,3),dtype=np.int32)
arr6

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
arr6.shape, arr6.ndim

((3, 3), 2)

In [35]:
# 2차원 => 1차원
arr7=arr6.flatten()
arr7

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# 1차원 => 다른 차원으로 변경 reshape()
arr8=arr7.reshape((3,3))
arr8

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
arr9=arr8.reshape((3,1,3))
arr9

array([[[0, 0, 0]],

       [[0, 0, 0]],

       [[0, 0, 0]]])

In [47]:
arr10=np.array(([1,2,3,4],[5,6,7,8]))
arr10.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr10.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr10.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
arr10.reshape((2,4,1))

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [52]:
arr10.reshape((4,2,1))

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [53]:
# 차원/형태 변환 => reshape(-1,n), reshape(n,-1)
arr11=np.arange(8)
arr11

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
arr12=arr11.reshape(-1,2)
arr12

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [57]:
# arr12=arr11.reshape(-1,3) => 에러 원소/행열 개수 안맞음 
# arr12