In [1]:
import tensorflow as tf
from keras import Sequential # 레이어를 선형으로 쌓는 모델 객체
from keras.layers import Dense # 레이어객체
from sklearn.datasets import load_iris
 
import numpy as np

In [2]:
# 데이터 로딩
iris=load_iris()
data=iris.data
target=iris.target
print(data.shape, target.shape)

(150, 4) (150,)


In [35]:
# 훈련 데이터셋과 테스트 데이터셋 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, target, shuffle=True,random_state=42)

In [36]:
# 모델 구성
model=Sequential(name='IRIS')

# 각 노드(퍼셉트론, 유닛): 4개 입력 / 1개 출력
# 총 10개가 다음 층의 입력
model.add(Dense(10, activation='relu', input_shape=(4,)))

# 각 노드(퍼셉트론, 유닛): 10개 입력 / 1개 출력
# 총 3개 출력
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "IRIS"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 10)                50        
                                                                 
 dense_8 (Dense)             (None, 3)                 33        
                                                                 
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


In [37]:
# 모델 생성

# categorical_crossentropy: 원핫인코딩 후 넣어야함
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [38]:
# 학습
model.fit(x_train, y_train)

4/4 [==============================] - 0s 2ms/step - loss: 5.8116 - accuracy: 0.3482


In [39]:
# 원핫인코딩
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

y_train2=ohe.fit(y_train.reshape(-1,1)).transform(y_train.reshape(-1,1))
y_train3=y_train2.toarray()

In [45]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train3, epochs=150)

Epoch 1/150
4/4 [==============================] - 1s 3ms/step - loss: 0.3277 - accuracy: 0.9375
Epoch 2/150
4/4 [==============================] - 0s 4ms/step - loss: 0.3251 - accuracy: 0.9554
Epoch 3/150
4/4 [==============================] - 0s 3ms/step - loss: 0.3225 - accuracy: 0.9554
Epoch 4/150
4/4 [==============================] - 0s 4ms/step - loss: 0.3215 - accuracy: 0.9554
Epoch 5/150
4/4 [==============================] - 0s 4ms/step - loss: 0.3185 - accuracy: 0.9643
Epoch 6/150
4/4 [==============================] - 0s 3ms/step - loss: 0.3174 - accuracy: 0.9643
Epoch 7/150
4/4 [==============================] - 0s 4ms/step - loss: 0.3161 - accuracy: 0.9554
Epoch 8/150
4/4 [==============================] - 0s 8ms/step - loss: 0.3147 - accuracy: 0.9643
Epoch 9/150
4/4 [==============================] - 0s 5ms/step - loss: 0.3125 - accuracy: 0.9464
Epoch 10/150
4/4 [==============================] - 0s 4ms/step - loss: 0.3112 - accuracy: 0.9375
Epoch 11/150
4/4 [===========

In [46]:
ohe=OneHotEncoder()
y_test2=ohe.fit(y_test.reshape(-1,1)).transform(y_test.reshape(-1,1))
y_test3=y_test2.toarray()

# 예측
print(model.predict(x_test))
print(y_test3)

2/2 [==============================] - 0s 3ms/step
[[1.24440133e-03 8.23658466e-01 1.75097078e-01]
 [9.94129419e-01 5.86999673e-03 5.92755612e-07]
 [7.69475417e-09 2.25715414e-02 9.77428436e-01]
 [1.22737698e-03 6.79928064e-01 3.18844497e-01]
 [6.14824763e-04 7.87197113e-01 2.12188035e-01]
 [9.90082562e-01 9.91480984e-03 2.60741285e-06]
 [2.41949148e-02 8.74604702e-01 1.01200372e-01]
 [1.89850634e-05 1.49408445e-01 8.50572526e-01]
 [1.73406050e-04 4.66406196e-01 5.33420444e-01]
 [8.53995048e-03 8.77955019e-01 1.13504946e-01]
 [8.54443642e-05 3.00347775e-01 6.99566841e-01]
 [9.87260282e-01 1.27356844e-02 3.99133251e-06]
 [9.95217621e-01 4.78173420e-03 5.93596894e-07]
 [9.87363160e-01 1.26335239e-02 3.30051057e-06]
 [9.95230079e-01 4.76910360e-03 7.19190723e-07]
 [1.59365870e-03 7.36357987e-01 2.62048334e-01]
 [1.31170054e-06 6.51316568e-02 9.34867084e-01]
 [6.54678792e-03 8.67807448e-01 1.25645742e-01]
 [1.58094114e-03 7.43727326e-01 2.54691631e-01]
 [1.21073208e-06 5.59008121e-02 9.440

In [47]:
# 평가
model.evaluate(x_test, y_test3)


2/2 [==============================] - 0s 5ms/step - loss: 0.1410 - accuracy: 0.9737


[0.14101991057395935, 0.9736841917037964]